name: Build Status

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run CLI tests
      run: |
        npm run cli -- --version
        npm run cli -- --help
        npm run cli -- ticket -c 1
        npm run cli -- sequence -c 1
      
    - name: Test example
      run: npm run example
      
    - name: Build package
      run: npm pack 